proto: "openocd"
openocd_conf: "/usr/share/openocd/scripts/board/st_nucleo_l1.cfg"
memory_map:
    ivt: {"base" : 0x00000000, "size" : 0x00001000,  "forwarded" : false}
    rom: {"base" : 0x00080000, "size" : 0x00080000,  "forwarded" : false}
    ram: {"base" : 0x20000000, "size" : 0x100000,  "forwarded" : false}
    mmio: {"base" : 0x40000000, "size" : 0x20000000,  "forwarded" : true}
#    nvic: {"base" : 0xE000E100, "size" : 0x00000008,  "forwarded" : true}
#    other: {"base" : 0xE0000000, "size" : 0x10000000, "forwarded" : true}
ignore_irqs: [15]
uart:
    rx: 0x400e081c
    tx: 0x400e081c
