proto: "openocd"
openocd_conf: "../openocd_scripts/max32600.ocd"
memory_map:
    rom: {"base" : 0x0, "size" : 0x00080000,  "forwarded" : false}
    ram: {"base" : 0x20000000, "size" : 0x00019000,  "forwarded" : false}
    mmio: {"base" : 0x40000000, "size": 0x18000000,  "forwarded" : true}
